#!/usr/bin/env python3
import argparse
import os
import matplotlib.pyplot as plt
import numpy as np
from scipy.ndimage import gaussian_filter1d

def smooth_data(rates, sigma=4.0):
    return gaussian_filter1d(rates, sigma=sigma)


def read_data(path):
   times = []
   rates = []
   with open(path, 'r') as f:
       for line in f:
           line = line.strip()
           if not line or line.startswith('#'):
               continue
           parts = line.split()
           if len(parts) >= 2:
               try:
                   times.append(float(parts[0]))
                   rates.append(float(parts[1]))
               except ValueError:
                   pass
   return times, rates


def plot(times, rates, out_path=None, smooth=True):
   if smooth:
      rates = smooth_data(rates)
   plt.rcParams['font.family'] = 'serif'
   fig, ax = plt.subplots(figsize=(8, 4))
   ax.plot(times, rates, color='tab:orange', linewidth=0.8)
   ax.set_xlabel('Wait Time (µs)')
   ax.set_ylabel('Eviction Percentage (%)')
   ax.set_ylim(0, 100)
   ax.grid(True)
   plt.tight_layout()
   if out_path:
       plt.savefig(out_path, format='pdf', bbox_inches='tight')
       print(f'Plot saved to {out_path}')
   else:
       plt.show()


def main():
   p = argparse.ArgumentParser(description='Plot eviction rate vs wait time')
   p.add_argument('file', help='data file generated by vset')
   p.add_argument('-o', '--output', help='output PDF file')
   args = p.parse_args()

   times, rates = read_data(args.file)
   if not times:
       p.error('no data found in file')
   
   if args.output:
       out_path = args.output
   else:
       base_name = os.path.splitext(args.file)[0]
       out_path = base_name + '.pdf'
   
   plot(times, rates, out_path)


if __name__ == '__main__':
   main()
